# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-06-27 12:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='phone',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='手机号'),
        ),
    ]
