# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-06-27 12:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_auto_20210627_2011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article2tag',
            name='doen_num',
        ),
        migrations.AddField(
            model_name='article2tag',
            name='down_num',
            field=models.BigIntegerField(default=0, verbose_name='点踩数'),
        ),
    ]
